
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile-pvclaim
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: my-azurefile-storage-class