apiVersion: v1
kind: Service
metadata:
  name: azure-files-nginx-service
  labels: 
    app: azure-files-app
spec:
  type: LoadBalancer
  selector:
    app: azure-files-app
  ports: 
    - port: 3000
      targetPort: 3000

