apiVersion: v1
kind: Service
metadata:
  name: backend-deploy-service1
  labels:
    app: backend-deploy1
spec:
  type: LoadBalancer
  selector:
    app: backend-deploy1
  ports:
    - port: 3000
      targetPort: 3000